### ISSUE TITLE
Not able to fulfill the "contact" form on Firefox and IE

### ISSUE THREAD

**Issue by JasminaPN** [keitaroinc/keitaro-theme#18]
Steps to reproduce the issue:
1.Firefox: on the following page https://new.keitaro.com/contact/ I am able to fulfill the fields (Company name and Business email), I am writing but there is no color on the text.
2. IE: on the following page https://new.keitaro.com/contact/ I am not able to fulfill the fields (Company name and Business email), I cannot write anything.

**Comment by gocemitevski** [comment]
@JasminaPN should be resolved now. Please test and close the issue if no further work is needed.

**Comment by JasminaPN** [comment]
Yes, the issue is tested and it is fixed. It will be closed.
