### ISSUE TITLE
Bad wrapping of text around author on posts

### ISSUE THREAD

**Issue by mbocevski** [keitaroinc/keitaro-theme#2]
On Google Chrome and Safari when viewing a post the wrapping of the text around the author "Contributed 1 post and 0 comments so far" is bad. On Firefox it looks good.

Screenshot attached, it looks exactly the same on Safari and Chrome:
<img width="1413" alt="screen shot 2018-01-11 at 11 57 59" src="https://user-images.githubusercontent.com/16955141/34822329-dcaca0b6-f6c6-11e7-8785-a8b3482fa456.png">

**Comment by gocemitevski** [comment]
@mbocevski this is related to the shape-outside CSS property, which gets ignored in Firefox.

**Comment by mbocevski** [comment]
@gocemitevski so this is inline with the design and it's a bug in Firefox?

**Comment by gocemitevski** [comment]
@mbocevski yes, it is how it was designed. It is not a Firefox bug, more like a missing feature that is yet to be supported. https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside

> 2. From version 53: this feature is behind the layout.css.shape-outside.enabled preference (needs to be set to true). To change preferences in Firefox, visit about:config.

**Comment by mbocevski** [comment]
Thanks. Closing as non-issue.
