### ISSUE TITLE
The attachment from Job application is not delivered

### ISSUE THREAD

**Issue by JasminaPN** [keitaroinc/keitaro-theme#31]
Steps to reproduce the issue:
1) on the following page https://new.keitaro.com/join-keitaro/ if the user attaches a file, the file is not delivered.
Note: tested from Gmail, working as expected. The issue occurs when Yahoo email is used.

**Comment by gocemitevski** [comment]
@JasminaPN should be resolved now. Please check and close the issue if resolved.

**Comment by JasminaPN** [comment]
The issue is resolved. It will be closed. Thanks @gocemitevski
