### ISSUE TITLE
Docker page should be opened in new tab

### ISSUE THREAD

**Issue by JasminaPN** [keitaroinc/keitaro-theme#7]
On home page by clicking the "docker" icon , docker page is opened on the same page. It should be opened in new tab.

**Comment by gocemitevski** [comment]
This is relevant for all icons with assigned links in the section, not just Docker.

**Comment by JasminaPN** [comment]
Yes, but at the moment they are not clickable, that is why they are  not mentioned.

**Comment by gocemitevski** [comment]
Resolved.

**Comment by JasminaPN** [comment]
I will close the issue because it is resolved and verified.
