### ISSUE TITLE
Keitaro Website - Insights Page - Page navigation is displayed twice

### ISSUE THREAD

**Issue by JasminaPN** [keitaroinc/keitaro-theme#90]
**Steps to recreate the issue:**

1. Go to the following link: https://www.keitaro.com/
2. In the main menu choose the "Insights" tab
3. In the "Search Bar" on the "Insights" page please add some keywords in order for the search option to be performed. For example, add the "ckan" - **Result:** The Search option will be performed and the results will be listed.
4. Scroll down to the bottom of the page and the navigation is displayed twice:
<img width="1440" alt="Screenshot 2023-01-30 at 10 05 04" src="https://user-images.githubusercontent.com/23238850/215433516-66d873ee-a3bc-4802-88f4-b9e70db1d037.png">

**Important note:** if the user doesn't add a keyword in the search bar on the Insights page, then the navigation is correct.

**Comment by gocemitevski** [comment]
@JasminaPN should be fixed now. Please test and close the issue if it looks good. Thanks!

**Comment by JasminaPN** [comment]
The issue is fixed. I will close this ticket.

Thanks, Goce
