### ISSUE TITLE
Fix mobile responsive title in partners page

### ISSUE THREAD

**Issue by ekoteva15** [keitaroinc/keitaro-theme#99]
The title in the [Partners page](https://www.keitaro.com/partners/) - (KEITARO IS A COMPANY WHERE PEOPLE WORK AND GROW!) is not responsive on mobile devices (see photo below).
![image](https://github.com/keitaroinc/keitaro-theme/assets/117171046/8bd5df1a-a594-4efe-925d-0a7f379724ad)

**Comment by gocemitevski** [comment]
@ekoteva15 should be fixed now. Please double check.

**Comment by ekoteva15** [comment]
@gocemitevski This looks good on Android ( first photo). On iOS, looks okay except for the splitted Compa-ny word (second photo, I don't know if this is an issue).
![partners-page-title-android-fix](https://github.com/keitaroinc/keitaro-theme/assets/117171046/c787b4c5-b963-45a7-97dd-ead7562d6e9a)


![partners-page-title-ios-fix](https://github.com/keitaroinc/keitaro-theme/assets/117171046/078de028-d998-419e-a526-f16325e704e1)

**Comment by gocemitevski** [comment]
@ekoteva15 thanks! Please double check once again and close the issue if it looks good.

**Comment by ekoteva15** [comment]
@gocemitevski this looks great now,  both on Android and iOS.
